### ISSUE TITLE
Shelly Plus 2PM not discovered

### ISSUE THREAD

**Issue by skloos68** [bieniu/ha-shellies-discovery-gen2#100]
After installation of the scripts according to the description all my Shelly Plus 2PM are not discovered. In the HA log files I see an error that I probably not solve. (see log below).

If I switch device profile to "cover" the shelly is discovered. in "Switch" profile not.

------------Automations ----------------------------------------------------
alias: Shellies Announce Gen2
trigger:
  - platform: homeassistant
    event: start
action:
  - repeat:
      for_each: "{{ device_ids }}"
      sequence:
        - service: mqtt.publish
          data:
            topic: "{{ repeat.item }}/rpc"
            payload: "{{ device_info_payload }}"
variables:
  device_info_payload: >-
    {{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} |
    to_json }}
  device_ids:
    - wss18
    - wss16
    **- shellyplus2pm-441793ad2fac** (device that is powered and active)

-----------
alias: Shellies Discovery Gen2
trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
mode: queued
max: 999
------------------------------------------------------

**Expected behavior**
shelly get's discovered after announce trigger

**Versions:**
 - Home Assistant: 2022.10.0 ( but also previous public version)
 - Shellies Discovery GEN2: Release 1.5.2 
 - Shelly device firmware: 0.11.2

**Shellies Discovery GEN2 automation:**

```yaml

```

**Debug log:**
2022-10-10 00:05:40.158 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeating sequence: Iteration 1 of 3 with item: 'wss18'
2022-10-10 00:05:40.158 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Running automation actions
2022-10-10 00:05:40.159 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Executing step call service
2022-10-10 00:05:40.162 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeating sequence: Iteration 2 of 3 with item: 'wss16'
2022-10-10 00:05:40.162 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Running automation actions
2022-10-10 00:05:40.162 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Executing step call service
2022-10-10 00:05:40.164 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeating sequence: Iteration 3 of 3 with item: 'shellyplus2pm-441793ad2fac'
2022-10-10 00:05:40.164 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Running automation actions
2022-10-10 00:05:40.164 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Executing step call service
2022-10-10 00:05:40.713 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Running automation actions
2022-10-10 00:05:40.713 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Executing step call service
2022-10-10 00:05:40.755 INFO (SyncWorker_8) [homeassistant.components.python_script] Executing shellies_discovery_gen2.py: {'id': 'shellyplus2pm-441793ad2fac', 'device_config': {'ble': {'enable': False}, 'cloud': {'enable': False, 'server': 'shelly-api-eu.shelly.cloud:6022/jrpc'}, 'input:0': {'id': 0, 'name': None, 'type': 'switch', 'invert': False, 'factory_reset': True}, 'input:1': {'id': 1, 'name': None, 'type': 'switch', 'invert': False, 'factory_reset': True}, 'mqtt': {'enable': True, 'server': 'mqtt.empurias.com:1883', 'client_id': 'shellyplus2pm-441793ad2fac', 'user': None, 'topic_prefix': 'shellyplus2pm-441793ad2fac', 'rpc_ntf': True, 'status_ntf': True}, 'script:1': {'id': 1, 'name': 'send_device_status.js', 'enable': True}, 'switch:0': {'id': 0, 'name': None, 'in_mode': 'follow', 'initial_state': 'match_input', 'auto_on': False, 'auto_on_delay': 60.0, 'auto_off': False, 'auto_off_delay': 60.0, 'power_limit': 2800, 'voltage_limit': 280, 'current_limit': 10.0}, 'switch:1': {'id': 1, 'name': None, 'in_mode': 'follow', 'initial_state': 'match_input', 'auto_on': False, 'auto_on_delay': 60.0, 'auto_off': False, 'auto_off_delay': 60.0, 'power_limit': 2800, 'voltage_limit': 280, 'current_limit': 10.0}, 'sys': {'device': {'name': 'wss16', 'mac': '441793AD2FAC', 'fw_id': '20221004-113507/0.11.2-g2ea2af3', 'discoverable': True, 'eco_mode': True, 'profile': 'switch'}, 'location': {'tz': 'Europe/Amsterdam', 'lat': 52.39424, 'lon': 4.84668}, 'debug': {'mqtt': {'enable': True}, 'websocket': {'enable': True}, 'udp': {'addr': None}}, 'ui_data': {}, 'rpc_udp': {'dst_addr': None, 'listen_port': None}, 'sntp': {'server': 'time.google.com'}, 'cfg_rev': 21}, 'wifi': {'ap': {'ssid': 'ShellyPlus2PM-441793AD2FAC', 'is_open': True, 'enable': False, 'range_extender': {'enable': False}}, 'sta': {'ssid': 'XIOT2', 'is_open': False, 'enable': True, 'ipv4mode': 'dhcp', 'ip': None, 'netmask': None, 'gw': None, 'nameserver': None}, 'sta1': {'ssid': None, 'is_open': True, 'enable': False, 'ipv4mode': 'dhcp', 'ip': None, 'netmask': None, 'gw': None, 'nameserver': None}, 'roam': {'rssi_thr': -80, 'interval': 60}}, 'ws': {'enable': False, 'server': None, 'ssl_ca': 'ca.pem'}}}
2022-10-10 00:05:40.756 ERROR (SyncWorker_8) [homeassistant.components.python_script.shellies_discovery_gen2.py] Error executing script: 'cover'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery_gen2.py", line 1396, in <module>
  File "shellies_discovery_gen2.py", line 1267, in configure_device
  File "shellies_discovery_gen2.py", line 1091, in get_sensor
KeyError: 'cover'

**Comment by skloos68** [comment]
Hi, thanks for the fast response. Unfortunately the issue  does not seem to be completely resolved.

2 issues:

situation:
1. installed the new python script version
2. restarted HA
3. The device is now recognized but,
       - the relays do not show up as controls
   (1)- all device specific sensors show up but grayed out
             -  my test device is set up as switch and next to relay's I see all Cover controls as well grayed out.
             - Power and energy sensors are also grayed-out
             - **expected behavior**: only Switch specific sensors would be visible
             
       - all generic sensors, (Wfi, update, etc seem fine)

4. To reproduce and make sure I was not too hasty; I removed the device from HA 
5. restarted HA (also restarted the docker instance separately as well as 2nd attempt)
(2) 6. and after waiting and manual triggering Gen2 Announce automation, the device is not recognized anymore/again

Since after trying to reproduce the device did not show up anymore, I do not have screenshots. Sorry.

Logging:
[home-assistant.log](https://github.com/bieniu/ha-shellies-discovery-gen2/files/9744356/home-assistant.log)

**Comment by bieniu** [comment]
This issue is closed. If you have other problem, open a new one.
