### ISSUE TITLE
add Shelly get NoneType error

### ISSUE THREAD

**Issue by Aswertus** [bieniu/ha-shellies-discovery-gen2#34]
I try to add my first Gen2 Shelly in HA with your script (ShellyPlus1); based on the log entries, the shelly is found, but then there is a problem and your script throws an error and a few messages.

Thank you for your help!
Regards,
Aswertus

**Versions:**
 - Home Assistant:  2022.2.2
 - Shellies Discovery GEN2: 1.1.0
 - Shelly device firmware: 0.9.3

**Shellies Discovery GEN2 automation:**
```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
  action:
    - service: mqtt.publish
      data:
        topic: "shellyplus1-esstisch/rpc"  # shellyplus1pm-112233445566 is a device ID
        payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"

- id: shellies_status_gen2
  alias: "Shellies Status Gen2"
  trigger:
  - platform: time_pattern
    minutes: "/15"
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: shellyplus1-esstisch/rpc #shellyplus1-441793a4b0c4
      payload: "{{ {'id': 1, 'src':'shellyplus1-esstisch/status', 'method':'Shelly.GetStatus'} | to_json }}"  # shellyplus1pm-112233445566 is a device ID

```

**Debug log:**

```
2022-02-11 01:18:09 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Running automation actions
2022-02-11 01:18:09 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Executing step call service
2022-02-11 01:18:09 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Running automation actions
2022-02-11 01:18:09 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Executing step call service
2022-02-11 01:18:09 INFO (SyncWorker_7) [homeassistant.components.python_script] Executing shellies_discovery_gen2.py: {'id': 'shellyplus1-441793a4b0c4', 'device_config': {'ble': {'enable': False}, 'cloud': {'enable': False, 'server': 'iot.shelly.cloud:6012/jrpc'}, 'input:0': {'id': 0, 'name': None, 'type': 'switch', 'invert': False, 'factory_reset': True}, 'mqtt': {'enable': True, 'server': '192.168.0.207:1883', 'user': 'mqttuser', 'pass': 'mqttpwd', 'topic_prefix': 'shellyplus1-esstisch', 'rpc_ntf': True, 'status_ntf': True}, 'script:1': {'id': 1, 'name': 'MQTT-Online', 'enable': True}, 'switch:0': {'id': 0, 'name': 'Esstisch', 'in_mode': 'follow', 'initial_state': 'off', 'auto_on': False, 'auto_on_delay': 60.0, 'auto_off': False, 'auto_off_delay': 60.0}, 'sys': {'device': {'name': None, 'mac': '441793A4B0C4', 'fw_id': '20220117-162816/0.9.3-g354c141', 'eco_mode': False}, 'location': {'tz': 'Europe/Vienna', 'lat': 48.36308, 'lon': 16.3218}, 'debug': {'mqtt': {'enable': False}, 'websocket': {'enable': False}, 'udp': {'addr': None}}, 'ui_data': {'consumption_types': ['lights']}, 'rpc_udp': {'dst_addr': None, 'listen_port': None}, 'sntp': {'server': '192.168.0.207'}, 'cfg_rev': 31}, 'wifi': {'ap': {'ssid': 'ShellyPlus1-441793A4B0C4', 'is_open': True, 'enable': False}, 'sta': {'ssid': 'Shelly27', 'is_open': False, 'enable': True, 'ipv4mode': 'static', 'ip': '192.168.0.231', 'netmask': '255.255.255.0', 'gw': '192.168.0.1', 'nameserver': '208.67.222.222'}, 'sta1': {'ssid': None, 'is_open': True, 'enable': False, 'ipv4mode': 'dhcp', 'ip': None, 'netmask': None, 'gw': None, 'nameserver': None}, 'roam': {'rssi_thr': -80, 'interval': 60}}}}
2022-02-11 01:18:09 ERROR (SyncWorker_7) [homeassistant.components.python_script.shellies_discovery_gen2.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery_gen2.py", line 1155, in 
  File "shellies_discovery_gen2.py", line 1020, in configure_device
TypeError: 'NoneType' object is not callable
```

[log.txt](https://github.com/bieniu/ha-shellies-discovery-gen2/files/8045185/log.txt)
[automation.txt](https://github.com/bieniu/ha-shellies-discovery-gen2/files/8045186/automation.txt)

**Comment by Aswertus** [comment]
OK! I guess I found the problem! You have a bug in your code

you write at line 1020

`in device_config["sys"]["ui_data"].get("consumption_types", {}).get(relay_id, "switch").lower()`

but as far as I can see there is nowhere else "ui_data" used. I replaceds it with 

`in device_config["sys"]["device"]`


adns yep! it works! the device is added successfully!

**Comment by Aswertus** [comment]
line 1020 must be changed to `in device_config["sys"]["device"]` to make the script work again

**Comment by bieniu** [comment]
Yo're not right, `consumption_types` are under `ui_data`:

![image](https://user-images.githubusercontent.com/478555/153553259-6d803890-8865-4197-9bfe-b2caea4b848e.png)
